---

- name: Gather packages info
  package_facts:
    manager: auto

- name: Install Oracle Java if not present
  when: '"jdk1.8" not in ansible_facts.packages'
  block:
  - name: Install Oracle Java if not present
    package:
      name: "{{ bootstrap_kafka__java_packages }}"
      state: present

