- name: Configure zookeeper
  lineinfile:
    path: /usr/local/zookeeper/conf/zoo_sample.cfg
    regexp: '^dataDir='
    line: 'dataDir=/var/zookeeper'
- blockinfile:
    dest: /usr/local/zookeeper/conf/zoo_sample.cfg
    insertafter: EOF
    state: present
    content: "\nserver.1={{IP1}}:2888:3888\nserver.2={{IP2}}:2888:3888\nserver.3={{IP3}}:2888:3888\n"
- name: Rename Configuration file
  copy:
    src: /usr/local/zookeeper/conf/zoo_sample.cfg
    dest: /usr/local/zookeeper/conf/zoo.cfg
    remote_src: yes
- file:
    path: /usr/local/zookeeper/conf/zoo_sample.cfg
    state: absent
- name: Changing ownership
  file:
    path: /usr/local/zookeeper/conf/zoo.cfg
    owner: zookeeper
    group: zookeeper
    mode: 0644
- name: Creating Log Directory
  file:
    path: /usr/local/zookeeper/logs
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: 0775
- name: Updating Log Properties
  lineinfile:
    path: /usr/local/zookeeper/conf/log4j.properties
    regexp: "{{ item.regexp1 }}"
    line: "{{ item.replace1 }}"
  with_items:
    - { regexp1: '^zookeeper.log.dir=', replace1: 'zookeeper.log.dir=/usr/local/zookeeper/logs' }
    - { regexp1: '^zookeeper.log.file=', replace1: 'zookeeper.log.file=zookeeper.log' }
- name: Configure Zookeeper ID
  file:
    path: /var/zookeeper/myid
    state: touch
    mode: 0644
    owner: zookeeper
    group: zookeeper
- copy:
    content: '1'
    dest: /var/zookeeper/myid
  when: 'ansible_default_ipv4.address == IP1'
- copy:
    content: '2'
    dest: /var/zookeeper/myid
  when: 'ansible_default_ipv4.address == IP2'
- copy:
    content: '3'
    dest: /var/zookeeper/myid
  when: 'ansible_default_ipv4.address == IP3'
